// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub fn is_finite_gf(result: u32, exp_bits: u32, mant_bits: u32) -> bool {
    let exp_mask: u32 = ((1 << exp_bits) - 1);
    let exp: u32 = ((result >> mant_bits) & exp_mask);
    return (exp != exp_mask);
}

pub fn is_finite_gf_h(result: u32, exp_bits: u32, mant_bits: u32, has_inf: u32) -> bool {
    let exp_mask: u32 = ((1 << exp_bits) - 1);
    let exp: u32 = ((result >> mant_bits) & exp_mask);
    if (has_inf == 1) {
        return (exp != exp_mask);
    } else {
        return (exp == exp);
    }
}

pub const FMT_GF_BINARY: u32 = 0;

pub const FMT_GFT16: u32 = 1;

pub fn gft_pow3(exp_trits: u32) -> u32 {
    if (exp_trits == 2) {
        return 9;
    }
    if (exp_trits == 3) {
        return 27;
    }
    if (exp_trits == 4) {
        return 81;
    }
    if (exp_trits == 5) {
        return 243;
    }
    if (exp_trits == 6) {
        return 729;
    }
    if (exp_trits == 7) {
        return 2187;
    }
    if (exp_trits == 8) {
        return 6561;
    }
    if (exp_trits == 9) {
        return 19683;
    }
    if (exp_trits == 14) {
        return 4782969;
    }
    return 0;
}

pub fn gft_offset_max(exp_trits: u32) -> u32 {
    return (gft_pow3(exp_trits) - 1);
}

pub fn gft_exp_trits_for_width(width: u32) -> u32 {
    if (width == 4) {
        return 2;
    }
    if (width == 8) {
        return 3;
    }
    if (width == 16) {
        return 4;
    }
    if (width == 32) {
        return 6;
    }
    if (width == 64) {
        return 9;
    }
    if (width == 128) {
        return 14;
    }
    return 0;
}

pub fn gft_offset_max_for_width(width: u32) -> u32 {
    let et: u32 = gft_exp_trits_for_width(width);
    if (et == 0) {
        return 0;
    } else {
        return gft_offset_max(et);
    }
}

pub fn is_finite_gft_n(offset: u32, exp_trits: u32) -> bool {
    return (offset != gft_offset_max(exp_trits));
}

pub fn gft_offset_in_range(offset: u32, exp_trits: u32) -> bool {
    return (offset < gft_pow3(exp_trits));
}

pub fn is_valid_gft(offset: u32, exp_trits: u32) -> bool {
    if (offset < gft_pow3(exp_trits)) {
        return (offset != gft_offset_max(exp_trits));
    } else {
        return (offset != offset);
    }
}

pub const GFT16_OFFSET_MAX: u32 = 80;

pub fn is_finite_gft16(offset: u32) -> bool {
    return is_finite_gft_n(offset, 4);
}

pub fn is_finite_dispatch(
    fmt_family: u32,
    value: u32,
    exp_bits: u32,
    mant_bits: u32,
    has_inf: u32,
    exp_trits: u32,
) -> bool {
    if (fmt_family == FMT_GFT16) {
        return is_finite_gft_n(value, exp_trits);
    } else {
        return is_finite_gf_h(value, exp_bits, mant_bits, has_inf);
    }
}
