// Generated from .t27 spec
// DO NOT EDIT — generated by t27c

pub fn tick(counter: u32) -> u32 {
    return (counter + 1);
}

pub fn capture(counter: u32) -> u32 {
    return counter;
}

pub fn elapsed(t_start: u32, t_end: u32) -> u32 {
    return (t_end).wrapping_sub(t_start);
}

pub fn twr_tof(t1: u32, t2: u32, t3: u32, t4: u32) -> u32 {
    return (((t4 - t1) - (t3 - t2)) >> 1);
}
