/* ============================================================================
   Generated from t27 spec: BandwidthAllocator
   DO NOT EDIT - generated by t27c gen-c
   phi^2 + 1/phi^2 = 3 | TRINITY
   ============================================================================ */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <assert.h>
#define t27_assert(c, m) do { if (!(c)) { __builtin_trap(); } } while (0)

#ifndef BANDWIDTHALLOCATOR_H
#define BANDWIDTHALLOCATOR_H

/* -------------------------------------------------------
   Constants
   ------------------------------------------------------- */

#define MAX_FLOWS 8
#define TOTAL_BANDWIDTH 1000
#define MIN_BANDWIDTH 10
#define MAX_BANDWIDTH 500
#define PRIORITY_LOW 1
#define PRIORITY_MEDIUM 2
#define PRIORITY_HIGH 3

/* -------------------------------------------------------
   Array value types ([T; N] lowers to a by-value struct)
   ------------------------------------------------------- */

typedef struct { uint32_t v[8]; } t27_arr_uint32_t_8;

/* -------------------------------------------------------
   Function prototypes
   ------------------------------------------------------- */

uint32_t create_flow_requirement(uint32_t flow_id, uint32_t priority, uint32_t min_bw, uint32_t current_bw);
uint32_t get_flow_id(uint32_t req);
uint32_t get_flow_priority(uint32_t req);
uint32_t get_min_bandwidth(uint32_t req);
uint32_t get_current_bandwidth(uint32_t req);
uint32_t create_allocation_state(uint32_t allocated, uint32_t pending, uint32_t fair_share, uint32_t last_update);
uint32_t get_allocated_bw(uint32_t state);
uint32_t get_pending_requests(uint32_t state);
uint32_t get_fair_share(uint32_t state);
uint32_t get_last_update(uint32_t state);
t27_arr_uint32_t_8 create_flow_array(uint32_t f0, uint32_t f1, uint32_t f2, uint32_t f3, uint32_t f4, uint32_t f5, uint32_t f6, uint32_t f7);
uint32_t get_flow_req(t27_arr_uint32_t_8 array, uint32_t index);
uint32_t calculate_fair_share(uint32_t total_bw, uint32_t flow_count);
uint32_t allocate_bandwidth(uint32_t state, uint32_t flow_req, uint32_t available_bw);
bool needs_more_bandwidth(uint32_t flow_req);
uint32_t update_flow_bandwidth(uint32_t flow_req, uint32_t new_bw);
uint32_t count_active_flows(t27_arr_uint32_t_8 flow_array);
uint32_t find_reclaimable_bandwidth(uint32_t state, t27_arr_uint32_t_8 flow_array);
t27_arr_uint32_t_8 prioritize_bandwidth(t27_arr_uint32_t_8 flow_array, uint32_t available_bw);

/* -------------------------------------------------------
   Function implementations
   ------------------------------------------------------- */

uint32_t create_flow_requirement(uint32_t flow_id, uint32_t priority, uint32_t min_bw, uint32_t current_bw) {
    return (((((flow_id & 0xFF) << 24) | ((priority & 0x3) << 22)) | ((min_bw & 0x3FF) << 12)) | (current_bw & 0xFFF));
}

uint32_t get_flow_id(uint32_t req) {
    return ((req >> 24) & 0xFF);
}

uint32_t get_flow_priority(uint32_t req) {
    return ((req >> 22) & 0x3);
}

uint32_t get_min_bandwidth(uint32_t req) {
    return ((req >> 12) & 0x3FF);
}

uint32_t get_current_bandwidth(uint32_t req) {
    return (req & 0xFFF);
}

uint32_t create_allocation_state(uint32_t allocated, uint32_t pending, uint32_t fair_share, uint32_t last_update) {
    return (((((allocated & 0x7FF) << 21) | ((pending & 0xFF) << 13)) | ((fair_share & 0x1FF) << 4)) | (last_update & 0xF));
}

uint32_t get_allocated_bw(uint32_t state) {
    return ((state >> 21) & 0x7FF);
}

uint32_t get_pending_requests(uint32_t state) {
    return ((state >> 13) & 0xFF);
}

uint32_t get_fair_share(uint32_t state) {
    return ((state >> 4) & 0x1FF);
}

uint32_t get_last_update(uint32_t state) {
    return (state & 0xF);
}

t27_arr_uint32_t_8 create_flow_array(uint32_t f0, uint32_t f1, uint32_t f2, uint32_t f3, uint32_t f4, uint32_t f5, uint32_t f6, uint32_t f7) {
    return (t27_arr_uint32_t_8){ .v = { f0, f1, f2, f3, f4, f5, f6, f7 } };
}

uint32_t get_flow_req(t27_arr_uint32_t_8 array, uint32_t index) {
    if ((index < 8)) {
        return array.v[index];
    }
    return 0;
}

uint32_t calculate_fair_share(uint32_t total_bw, uint32_t flow_count) {
    if ((flow_count == 0)) {
        return 0;
    }
    return (total_bw / flow_count);
}

uint32_t allocate_bandwidth(uint32_t state, uint32_t flow_req, uint32_t available_bw) {
    int priority = get_flow_priority(flow_req);
    int min_bw = get_min_bandwidth(flow_req);
    int allocated = get_allocated_bw(state);
    uint32_t allocation = 0;
    if ((priority == PRIORITY_HIGH)) {
        allocation = (min_bw + ((available_bw * 7) / 10));
    } else if ((priority == PRIORITY_MEDIUM)) {
        allocation = calculate_fair_share(available_bw, 2);
    } else {
        allocation = min_bw;
    }
    if ((allocation > available_bw)) {
        allocation = available_bw;
    }
    if ((allocation > MAX_BANDWIDTH)) {
        allocation = MAX_BANDWIDTH;
    }
    if ((allocation < min_bw)) {
        allocation = min_bw;
    }
    int new_allocated = (allocated + allocation);
    int pending = get_pending_requests(state);
    int fair_share = get_fair_share(state);
    int update = get_last_update(state);
    return create_allocation_state(new_allocated, pending, fair_share, update);
}

bool needs_more_bandwidth(uint32_t flow_req) {
    int current = get_current_bandwidth(flow_req);
    int min_bw = get_min_bandwidth(flow_req);
    return (current < min_bw);
}

uint32_t update_flow_bandwidth(uint32_t flow_req, uint32_t new_bw) {
    int flow_id = get_flow_id(flow_req);
    int priority = get_flow_priority(flow_req);
    int min_bw = get_min_bandwidth(flow_req);
    if ((new_bw < min_bw)) {
        new_bw = min_bw;
    }
    if ((new_bw > MAX_BANDWIDTH)) {
        new_bw = MAX_BANDWIDTH;
    }
    return create_flow_requirement(flow_id, priority, min_bw, new_bw);
}

uint32_t count_active_flows(t27_arr_uint32_t_8 flow_array) {
    uint32_t count = 0;
    if ((get_current_bandwidth(get_flow_req(flow_array, 0)) > 0)) {
        count = (count + 1);
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 1)) > 0)) {
        count = (count + 1);
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 2)) > 0)) {
        count = (count + 1);
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 3)) > 0)) {
        count = (count + 1);
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 4)) > 0)) {
        count = (count + 1);
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 5)) > 0)) {
        count = (count + 1);
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 6)) > 0)) {
        count = (count + 1);
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 7)) > 0)) {
        count = (count + 1);
    }
    return count;
}

uint32_t find_reclaimable_bandwidth(uint32_t state, t27_arr_uint32_t_8 flow_array) {
    int allocated = get_allocated_bw(state);
    uint32_t total_used = 0;
    if ((get_current_bandwidth(get_flow_req(flow_array, 0)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 0)));
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 1)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 1)));
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 2)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 2)));
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 3)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 3)));
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 4)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 4)));
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 5)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 5)));
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 6)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 6)));
    }
    if ((get_current_bandwidth(get_flow_req(flow_array, 7)) > 0)) {
        total_used = (total_used + get_current_bandwidth(get_flow_req(flow_array, 7)));
    }
    if ((allocated > total_used)) {
        return (allocated - total_used);
    }
    return 0;
}

t27_arr_uint32_t_8 prioritize_bandwidth(t27_arr_uint32_t_8 flow_array, uint32_t available_bw) {
    int remaining_bw = available_bw;
    int f0 = get_flow_req(flow_array, 0);
    int f1 = get_flow_req(flow_array, 1);
    int f2 = get_flow_req(flow_array, 2);
    int f3 = get_flow_req(flow_array, 3);
    int f4 = get_flow_req(flow_array, 4);
    int f5 = get_flow_req(flow_array, 5);
    int f6 = get_flow_req(flow_array, 6);
    int f7 = get_flow_req(flow_array, 7);
    return create_flow_array(update_flow_bandwidth(f0, calculate_fair_share(remaining_bw, 8)), update_flow_bandwidth(f1, calculate_fair_share(remaining_bw, 8)), update_flow_bandwidth(f2, calculate_fair_share(remaining_bw, 8)), update_flow_bandwidth(f3, calculate_fair_share(remaining_bw, 8)), update_flow_bandwidth(f4, calculate_fair_share(remaining_bw, 8)), update_flow_bandwidth(f5, calculate_fair_share(remaining_bw, 8)), update_flow_bandwidth(f6, calculate_fair_share(remaining_bw, 8)), update_flow_bandwidth(f7, calculate_fair_share(remaining_bw, 8)));
}

/* -------------------------------------------------------
   Tests
   ------------------------------------------------------- */

void test_create_flow_requirement_basic(void) {
    uint64_t flow = create_flow_requirement(5, PRIORITY_HIGH, 50, 100);
    (void)flow;
    t27_assert((get_flow_id(flow) == 5), "flow ID");
    t27_assert((get_flow_priority(flow) == PRIORITY_HIGH), "high priority");
    t27_assert((get_min_bandwidth(flow) == 50), "min bandwidth");
    t27_assert((get_current_bandwidth(flow) == 100), "current bandwidth");
}

void test_create_allocation_state_basic(void) {
    uint64_t state = create_allocation_state(500, 3, 125, 10);
    (void)state;
    t27_assert((get_allocated_bw(state) == 500), "allocated bandwidth");
    t27_assert((get_pending_requests(state) == 3), "pending requests");
    t27_assert((get_fair_share(state) == 125), "fair share");
    t27_assert((get_last_update(state) == 10), "last update");
}

void test_calculate_fair_share_normal(void) {
    int share = calculate_fair_share(1000, 8);
    t27_assert((share == 125), "fair share for 8 flows");
}

void test_calculate_fair_share_zero_flows(void) {
    t27_assert((calculate_fair_share(1000, 0) == 0), "no flows = no share");
}

void test_allocate_bandwidth_high_priority(void) {
    uint64_t state = create_allocation_state(200, 1, 100, 0);
    (void)state;
    uint64_t flow = create_flow_requirement(5, PRIORITY_HIGH, 50, 100);
    (void)flow;
    uint64_t new_state = allocate_bandwidth(state, flow, 300);
    (void)new_state;
    t27_assert((get_allocated_bw(new_state) >= 400), "high priority allocation");
}

void test_allocate_bandwidth_medium_priority(void) {
    uint64_t state = create_allocation_state(200, 1, 100, 0);
    (void)state;
    uint64_t flow = create_flow_requirement(5, PRIORITY_MEDIUM, 50, 100);
    (void)flow;
    uint64_t new_state = allocate_bandwidth(state, flow, 200);
    (void)new_state;
    t27_assert((get_allocated_bw(new_state) >= 200), "medium priority allocation");
}

void test_allocate_bandwidth_low_priority(void) {
    uint64_t state = create_allocation_state(200, 1, 100, 0);
    (void)state;
    uint64_t flow = create_flow_requirement(5, PRIORITY_LOW, 50, 100);
    (void)flow;
    uint64_t new_state = allocate_bandwidth(state, flow, 200);
    (void)new_state;
    t27_assert((get_allocated_bw(new_state) >= 250), "low priority allocation");
}

void test_needs_more_bandwidth_true(void) {
    uint64_t flow = create_flow_requirement(5, PRIORITY_HIGH, 100, 50);
    (void)flow;
    t27_assert((needs_more_bandwidth(flow) == true), "needs more bandwidth");
}

void test_needs_more_bandwidth_false(void) {
    uint64_t flow = create_flow_requirement(5, PRIORITY_HIGH, 50, 100);
    (void)flow;
    t27_assert((needs_more_bandwidth(flow) == false), "sufficient bandwidth");
}

void test_update_flow_bandwidth_increase(void) {
    uint64_t flow = create_flow_requirement(5, PRIORITY_HIGH, 50, 100);
    (void)flow;
    uint64_t new_flow = update_flow_bandwidth(flow, 200);
    (void)new_flow;
    t27_assert((get_current_bandwidth(new_flow) == 200), "bandwidth increased");
}

void test_update_flow_bandwidth_respects_min(void) {
    uint64_t flow = create_flow_requirement(5, PRIORITY_HIGH, 50, 100);
    (void)flow;
    uint64_t new_flow = update_flow_bandwidth(flow, 30);
    (void)new_flow;
    t27_assert((get_current_bandwidth(new_flow) == 50), "minimum bandwidth respected");
}

void test_update_flow_bandwidth_respects_max(void) {
    uint64_t flow = create_flow_requirement(5, PRIORITY_HIGH, 50, 100);
    (void)flow;
    uint64_t new_flow = update_flow_bandwidth(flow, 600);
    (void)new_flow;
    t27_assert((get_current_bandwidth(new_flow) == MAX_BANDWIDTH), "maximum bandwidth respected");
}

void test_count_active_flows_full(void) {
    t27_arr_uint32_t_8 flow_array = create_flow_array(create_flow_requirement(1, PRIORITY_HIGH, 50, 100), create_flow_requirement(2, PRIORITY_MEDIUM, 40, 80), create_flow_requirement(3, PRIORITY_LOW, 30, 60), create_flow_requirement(4, PRIORITY_HIGH, 70, 120), create_flow_requirement(5, PRIORITY_MEDIUM, 35, 70), create_flow_requirement(6, PRIORITY_LOW, 25, 50), create_flow_requirement(7, PRIORITY_HIGH, 60, 110), create_flow_requirement(8, PRIORITY_LOW, 20, 40));
    (void)flow_array;
    t27_assert((count_active_flows(flow_array) == 8), "8 active flows");
}

void test_count_active_flows_partial(void) {
    t27_arr_uint32_t_8 flow_array = create_flow_array(create_flow_requirement(1, PRIORITY_HIGH, 50, 100), create_flow_requirement(2, PRIORITY_MEDIUM, 40, 0), create_flow_requirement(3, PRIORITY_LOW, 30, 60), create_flow_requirement(4, PRIORITY_HIGH, 70, 0), 0, 0, 0, 0);
    (void)flow_array;
    t27_assert((count_active_flows(flow_array) == 2), "2 active flows");
}

void test_find_reclaimable_bandwidth(void) {
    uint64_t state = create_allocation_state(500, 1, 100, 0);
    (void)state;
    t27_arr_uint32_t_8 flow_array = create_flow_array(create_flow_requirement(1, PRIORITY_HIGH, 50, 100), create_flow_requirement(2, PRIORITY_MEDIUM, 40, 80), create_flow_requirement(3, PRIORITY_LOW, 30, 60), create_flow_requirement(4, PRIORITY_HIGH, 70, 120), 0, 0, 0, 0);
    (void)flow_array;
    int reclaimable = find_reclaimable_bandwidth(state, flow_array);
    int total_used = (((100 + 80) + 60) + 120);
    t27_assert((reclaimable == (500 - total_used)), "reclaimable bandwidth calculated");
}

void test_prioritize_bandwidth_distributes(void) {
    t27_arr_uint32_t_8 flow_array = create_flow_array(create_flow_requirement(1, PRIORITY_HIGH, 50, 100), create_flow_requirement(2, PRIORITY_MEDIUM, 40, 80), create_flow_requirement(3, PRIORITY_LOW, 30, 60), create_flow_requirement(4, PRIORITY_HIGH, 70, 120), 0, 0, 0, 0);
    (void)flow_array;
    t27_arr_uint32_t_8 new_array = prioritize_bandwidth(flow_array, 800);
    t27_assert((get_current_bandwidth(get_flow_req(new_array, 0)) == 100), "flow 0 bandwidth");
    t27_assert((get_current_bandwidth(get_flow_req(new_array, 1)) == 100), "flow 1 bandwidth");
}


/* -------------------------------------------------------
   Test runner (compile with -DT27_TEST_MAIN to execute)
   ------------------------------------------------------- */

#ifdef T27_TEST_MAIN
#include <stdio.h>
int main(void) {
    test_create_flow_requirement_basic();
    test_create_allocation_state_basic();
    test_calculate_fair_share_normal();
    test_calculate_fair_share_zero_flows();
    test_allocate_bandwidth_high_priority();
    test_allocate_bandwidth_medium_priority();
    test_allocate_bandwidth_low_priority();
    test_needs_more_bandwidth_true();
    test_needs_more_bandwidth_false();
    test_update_flow_bandwidth_increase();
    test_update_flow_bandwidth_respects_min();
    test_update_flow_bandwidth_respects_max();
    test_count_active_flows_full();
    test_count_active_flows_partial();
    test_find_reclaimable_bandwidth();
    test_prioritize_bandwidth_distributes();
    printf("All %d tests passed.\n", 16);
    return 0;
}
#endif /* T27_TEST_MAIN */

#endif /* BANDWIDTHALLOCATOR_H */
