/* ============================================================================
   Generated from t27 spec: MeshProtocolStack
   DO NOT EDIT - generated by t27c gen-c
   phi^2 + 1/phi^2 = 3 | TRINITY
   ============================================================================ */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <assert.h>
#define t27_assert(c, m) do { if (!(c)) { __builtin_trap(); } } while (0)

#ifndef MESHPROTOCOLSTACK_H
#define MESHPROTOCOLSTACK_H

/* -------------------------------------------------------
   Tuple types
   ------------------------------------------------------- */

typedef struct { uint32_t f0; bool f1; } t27_tuple_uint32_t_bool;
typedef struct { uint32_t f0; bool f1; uint32_t f2; } t27_tuple_uint32_t_bool_uint32_t;

/* -------------------------------------------------------
   Constants
   ------------------------------------------------------- */

#define MAX_NODES 3
#define MAX_HOPS 3
#define NODE_A 1
#define NODE_B 2
#define NODE_C 3

/* -------------------------------------------------------
   Function prototypes
   ------------------------------------------------------- */

uint32_t build_packet(uint32_t src, uint32_t dst, uint8_t ttl, uint8_t payload);
uint32_t extract_src(uint32_t packet);
uint32_t extract_dst(uint32_t packet);
uint8_t extract_ttl(uint32_t packet);
uint8_t extract_payload(uint32_t packet);
t27_tuple_uint32_t_bool decrement_ttl(uint32_t packet);
uint32_t route_packet(uint32_t src, uint32_t dst, uint32_t next_hop);
uint32_t tx_path(uint32_t src, uint32_t dst, uint8_t payload);
uint8_t rx_path(uint32_t packet);
t27_tuple_uint32_t_bool_uint32_t forward_packet(uint32_t packet, uint32_t current_node);

/* -------------------------------------------------------
   Function implementations
   ------------------------------------------------------- */

uint32_t build_packet(uint32_t src, uint32_t dst, uint8_t ttl, uint8_t payload) {
    return (((((src & 0xFF) << 24) | ((dst & 0xFF) << 16)) | ((((uint32_t)(ttl)) & 0xF) << 12)) | (((uint32_t)(payload)) & 0xFF));
}

uint32_t extract_src(uint32_t packet) {
    return ((packet >> 24) & 0xFF);
}

uint32_t extract_dst(uint32_t packet) {
    return ((packet >> 16) & 0xFF);
}

uint8_t extract_ttl(uint32_t packet) {
    return ((uint8_t)(((packet >> 12) & 0xF)));
}

uint8_t extract_payload(uint32_t packet) {
    return ((uint8_t)((packet & 0xFF)));
}

t27_tuple_uint32_t_bool decrement_ttl(uint32_t packet) {
    if ((extract_ttl(packet) > 0)) {
        return (t27_tuple_uint32_t_bool){ ((packet & 0xFFFF0FFF) | ((((uint32_t)((extract_ttl(packet) - 1))) & 0xF) << 12)), (extract_ttl(packet) == 1) };
    } else {
        return (t27_tuple_uint32_t_bool){ packet, true };
    }
}

uint32_t route_packet(uint32_t src, uint32_t dst, uint32_t next_hop) {
    if (((src == NODE_A) && (dst == NODE_B))) {
        return NODE_B;
    } else if (((src == NODE_A) && (dst == NODE_C))) {
        return NODE_B;
    } else if (((src == NODE_B) && (dst == NODE_C))) {
        return NODE_C;
    } else if (((src == NODE_B) && (dst == NODE_A))) {
        return NODE_A;
    } else if (((src == NODE_C) && (dst == NODE_A))) {
        return NODE_B;
    } else if (((src == NODE_C) && (dst == NODE_B))) {
        return NODE_B;
    } else {
        return 0;
    }
}

uint32_t tx_path(uint32_t src, uint32_t dst, uint8_t payload) {
    return build_packet(src, dst, ((uint8_t)(MAX_HOPS)), payload);
}

uint8_t rx_path(uint32_t packet) {
    return extract_payload(packet);
}

t27_tuple_uint32_t_bool_uint32_t forward_packet(uint32_t packet, uint32_t current_node) {
    t27_tuple_uint32_t_bool __t_c85 = decrement_ttl(packet);
    uint32_t new_pkt = __t_c85.f0;
    bool expired = __t_c85.f1;
    if (expired) {
        return (t27_tuple_uint32_t_bool_uint32_t){ new_pkt, true, 0 };
    }
    if ((route_packet(current_node, extract_dst(new_pkt), 0) == 0)) {
        return (t27_tuple_uint32_t_bool_uint32_t){ new_pkt, false, 0 };
    }
    return (t27_tuple_uint32_t_bool_uint32_t){ new_pkt, false, route_packet(current_node, extract_dst(new_pkt), 0) };
}

/* -------------------------------------------------------
   Tests
   ------------------------------------------------------- */

void test_build_packet_correct_layout(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 3, 5);
    (void)pkt;
    t27_assert((extract_src(pkt) == NODE_A), "src preserved");
    t27_assert((extract_dst(pkt) == NODE_B), "dst preserved");
    t27_assert((extract_ttl(pkt) == 3), "ttl preserved");
    t27_assert((extract_payload(pkt) == 5), "payload preserved");
}

void test_tx_path_produces_valid_packet(void) {
    uint64_t pkt = tx_path(NODE_A, NODE_B, 7);
    (void)pkt;
    t27_assert((extract_src(pkt) == NODE_A), "tx src");
    t27_assert((extract_dst(pkt) == NODE_B), "tx dst");
    t27_assert((extract_payload(pkt) == 7), "tx payload");
}

void test_rx_path_extracts_payload(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 3, 9);
    (void)pkt;
    uint64_t payload = rx_path(pkt);
    (void)payload;
    t27_assert((payload == 9), "rx payload");
}

void test_decrement_ttl_reduces(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 3, 5);
    (void)pkt;
    __auto_type __t27_tup1 = decrement_ttl(pkt);
    __auto_type new_pkt = __t27_tup1.f0;
    (void)new_pkt;
    __auto_type expired = __t27_tup1.f1;
    (void)expired;
    t27_assert((extract_ttl(new_pkt) == 2), "ttl decremented");
    t27_assert((expired == false), "not expired");
}

void test_decrement_ttl_zero_expires(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 1, 5);
    (void)pkt;
    __auto_type __t27_tup1 = decrement_ttl(pkt);
    __auto_type new_pkt = __t27_tup1.f0;
    (void)new_pkt;
    __auto_type expired = __t27_tup1.f1;
    (void)expired;
    t27_assert((extract_ttl(new_pkt) == 0), "ttl zero");
    t27_assert((expired == true), "expired");
}

void test_decrement_ttl_already_expired(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 0, 5);
    (void)pkt;
    __auto_type __t27_tup1 = decrement_ttl(pkt);
    __auto_type new_pkt = __t27_tup1.f0;
    (void)new_pkt;
    __auto_type expired = __t27_tup1.f1;
    (void)expired;
    t27_assert((extract_ttl(new_pkt) == 0), "ttl zero");
    t27_assert((expired == true), "expired");
}

void test_route_packet_direct_a_to_b(void) {
    uint64_t next_hop = route_packet(NODE_A, NODE_B, 0);
    (void)next_hop;
    t27_assert((next_hop == NODE_B), "direct route AâB");
}

void test_route_packet_via_b_a_to_c(void) {
    uint64_t next_hop = route_packet(NODE_A, NODE_C, 0);
    (void)next_hop;
    t27_assert((next_hop == NODE_B), "route AâC via B");
}

void test_route_packet_direct_b_to_c(void) {
    uint64_t next_hop = route_packet(NODE_B, NODE_C, 0);
    (void)next_hop;
    t27_assert((next_hop == NODE_C), "direct route BâC");
}

void test_forward_packet_decrements_ttl(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 3, 5);
    (void)pkt;
    __auto_type __t27_tup1 = forward_packet(pkt, NODE_A);
    __auto_type new_pkt = __t27_tup1.f0;
    (void)new_pkt;
    __auto_type expired = __t27_tup1.f1;
    (void)expired;
    __auto_type next_hop = __t27_tup1.f2;
    (void)next_hop;
    t27_assert((extract_ttl(new_pkt) == 2), "ttl decreased");
    t27_assert((expired == false), "not expired");
    t27_assert((next_hop == NODE_B), "next hop B");
}

void test_forward_packet_preserves_payload(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 3, 5);
    (void)pkt;
    __auto_type __t27_tup1 = forward_packet(pkt, NODE_A);
    __auto_type fwd = __t27_tup1.f0;
    (void)fwd;
    t27_assert((extract_ttl(fwd) == 2), "only the TTL changes (3 -> 2)");
    t27_assert((extract_src(fwd) == NODE_A), "src preserved across the hop");
    t27_assert((extract_dst(fwd) == NODE_B), "dst preserved across the hop");
    t27_assert((extract_payload(fwd) == 5), "payload preserved across the hop");
    __auto_type __t27_tup2 = forward_packet(fwd, NODE_A);
    __auto_type fwd2 = __t27_tup2.f0;
    (void)fwd2;
    t27_assert((extract_payload(fwd2) == 5), "payload preserved after a second hop");
    t27_assert((extract_src(fwd2) == NODE_A), "src still preserved");
    t27_assert((extract_dst(fwd2) == NODE_B), "dst still preserved");
    t27_assert((extract_ttl(fwd2) == 1), "TTL 2 -> 1 on the second hop");
}

void test_forward_packet_ttl_expired(void) {
    uint64_t pkt = build_packet(NODE_A, NODE_B, 1, 5);
    (void)pkt;
    __auto_type __t27_tup1 = forward_packet(pkt, NODE_A);
    __auto_type pkt1 = __t27_tup1.f0;
    (void)pkt1;
    __auto_type exp1 = __t27_tup1.f1;
    (void)exp1;
    __auto_type __t27_tup2 = forward_packet(pkt1, NODE_B);
    __auto_type pkt2 = __t27_tup2.f0;
    (void)pkt2;
    __auto_type exp2 = __t27_tup2.f1;
    (void)exp2;
    t27_assert((exp2 == true), "expired after 2 hops");
}

void test_forward_packet_no_route(void) {
    uint64_t pkt = build_packet(NODE_A, 99, 3, 5);
    (void)pkt;
    __auto_type __t27_tup1 = forward_packet(pkt, NODE_A);
    __auto_type new_pkt = __t27_tup1.f0;
    (void)new_pkt;
    __auto_type expired = __t27_tup1.f1;
    (void)expired;
    __auto_type next_hop = __t27_tup1.f2;
    (void)next_hop;
    t27_assert((next_hop == 0), "no route");
    t27_assert((expired == false), "ttl not expired yet");
}

void test_end_to_end_tx_rx(void) {
    uint64_t pkt = tx_path(NODE_A, NODE_B, 42);
    (void)pkt;
    uint64_t payload = rx_path(pkt);
    (void)payload;
    t27_assert((payload == 42), "end-to-end payload");
}

void test_multi_hop_routing(void) {
    uint64_t pkt = tx_path(NODE_A, NODE_C, 7);
    (void)pkt;
    __auto_type __t27_tup1 = forward_packet(pkt, NODE_A);
    __auto_type pkt1 = __t27_tup1.f0;
    (void)pkt1;
    __auto_type exp1 = __t27_tup1.f1;
    (void)exp1;
    __auto_type hop1 = __t27_tup1.f2;
    (void)hop1;
    t27_assert((hop1 == NODE_B), "first hop to B");
    t27_assert((exp1 == false), "not expired");
    __auto_type __t27_tup2 = forward_packet(pkt1, NODE_B);
    __auto_type pkt2 = __t27_tup2.f0;
    (void)pkt2;
    __auto_type exp2 = __t27_tup2.f1;
    (void)exp2;
    __auto_type hop2 = __t27_tup2.f2;
    (void)hop2;
    t27_assert((hop2 == NODE_C), "second hop to C");
    t27_assert((exp2 == false), "not expired");
    uint64_t payload = rx_path(pkt2);
    (void)payload;
    t27_assert((payload == 7), "multi-hop payload");
}


/* -------------------------------------------------------
   Test runner (compile with -DT27_TEST_MAIN to execute)
   ------------------------------------------------------- */

#ifdef T27_TEST_MAIN
#include <stdio.h>
int main(void) {
    test_build_packet_correct_layout();
    test_tx_path_produces_valid_packet();
    test_rx_path_extracts_payload();
    test_decrement_ttl_reduces();
    test_decrement_ttl_zero_expires();
    test_decrement_ttl_already_expired();
    test_route_packet_direct_a_to_b();
    test_route_packet_via_b_a_to_c();
    test_route_packet_direct_b_to_c();
    test_forward_packet_decrements_ttl();
    test_forward_packet_preserves_payload();
    test_forward_packet_ttl_expired();
    test_forward_packet_no_route();
    test_end_to_end_tx_rx();
    test_multi_hop_routing();
    printf("All %d tests passed.\n", 15);
    return 0;
}
#endif /* T27_TEST_MAIN */

#endif /* MESHPROTOCOLSTACK_H */
