set_property PACKAGE_PIN C20 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property PACKAGE_PIN D19 [get_ports din]
set_property IOSTANDARD LVCMOS33 [get_ports din]
set_property PACKAGE_PIN D20 [get_ports dout]
set_property IOSTANDARD LVCMOS33 [get_ports dout]
